services:
  web:
    build: .
    command: bash entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DJANGO_SECRET_KEY: "django-insecure-placeholder"
      DJANGO_DEBUG: "1"
